development:
  adapter: postgresql
  host: 127.0.0.1
  database: sample-development

test:
  adapter: postgresql
  host: 127.0.0.1
  database: sample-test

production:
  adapter: postgresql
  host: 127.0.0.1
  database: sample-production
